[package]
name = "rustfm"
version = "0.0.2"

authors = ["Roxas Shadow <webmaster@giovannicapuano.net>"]
license = "WTFPL"

description = "A Rust interface for Last.fm APIs"
repository  = "https://github.com/RoxasShadow/rustfm"
keywords    = ["lastfm"]

[lib]
name = "rustfm"
path = "src/lib.rs"

[dependencies]
rustc-serialize = "0.3"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
