[package]
name = "rustfm"
version = "0.1.0"

authors = ["Roxas Shadow <webmaster@giovannicapuano.net>"]
license = "WTFPL"

description = "A Rust interface for Last.fm APIs"
repository  = "https://github.com/RoxasShadow/rustfm"
keywords    = ["lastfm"]

[lib]
name = "rustfm"
path = "src/lib.rs"

[dependencies]
serde        = "0.8"
serde_json   = "0.8"
serde_macros = "0.8"

hyper       = "0.9"
url         = "1.2"
lazy_static = "0.2"
